name: Windows

on:
  push:
  workflow_dispatch:

jobs:

  ci:
    runs-on: windows-latest
    steps:
      - name: Support longpaths
        run: git config --system core.longpaths true
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Retrieve versions.properties
        run: |
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/sireum/kekinian/master/versions.properties" -OutFile "versions.properties"
      - name: Cache Java
        id: cache-java
        uses: actions/cache@v3
        with:
          path: bin\win\java
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-java
      - name: Cache Scala
        id: cache-scala
        uses: actions/cache@v3
        with:
          path: bin\scala
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-scala
      - name: Cache Coursier
        id: cache-coursier
        uses: actions/cache@v3
        with:
          path: cache\coursier
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-coursier
      - name: Check LongPathsEnabled
        run: |
          (Get-ItemProperty "HKLM:System\CurrentControlSet\Control\FileSystem").LongPathsEnabled
      - name: Test
        shell: cmd
        run: |
          set COURSIER_CACHE=%GITHUB_WORKSPACE%\cache\coursier
          cd /d %GITHUB_WORKSPACE%
          set errorlevel=
          call bin\build.cmd test || goto :error
          goto :EOF
          :error
          exit /b %errorlevel%
